m=int(input('digite o número à ser multiplicado: '))
print('cá está sua tabela de {}'.format(m))
print('{} x {} = {}'.format(m,1,m*1))
print('{} x {} = {}'.format(m,2,m*2))
print('{} x {} = {}'.format(m,3,m*3))
print('{} x {} = {}'.format(m,4,m*4))
print('{} x {} = {}'.format(m,5,m*5))
print('{} x {} = {}'.format(m,6,m*6))
print('{} x {} = {}'.format(m,7,m*7))
print('{} x {} = {}'.format(m,8,m*8))
print('{} x {} = {}'.format(m,9,m*9))
print('{} x {} = {}'.format(m,10,m*10))
print('---'*10)