e=input('digite algo para ser analisado: ')
print('tipo:',type(e))
print('tem espaços?:',e.isspace())
print('é numérico?: ',e.isnumeric())
print('é alpha?: ',e.isalpha())
print('é alfabético?: ',e.isalpha())
print('é alfanumérico?: ',e.isalnum())
print('tem letras maiúsculas?: ',e.isupper())
print('tem letras minúsculas?: ',e.islower())
print('capitalizado:',e.istitle())
